
# Echo server
#############
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grpc-echo-server
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: grpc-echo
        role: server
      annotations:
        time: "{{ TIME }}"
        git-sha: "{{ GIT-SHA }}"
        whoami: "{{ WHOAMI }}"
    spec:
      containers:
      - name: grpc-echo-server
        image: "examples/grpc-echo-server:{{ IMAGE_TAG }}"
        ports:
        - containerPort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-echo-server
  labels:
    app: grpc-echo
spec:
  ports:
    - port: 30002
      protocol: TCP
  selector:
    app: grpc-echo
    role: server


# HTTP Bridge
#############
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grpc-echo-http-bridge
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: grpc-echo
        role: http-bridge
      annotations:
        time: "{{ TIME }}"
        git-sha: "{{ GIT-SHA }}"
        whoami: "{{ WHOAMI }}"
    spec:
      containers:
      - name: grpc-echo-http-bridge
        image: examples/grpc-echo-http-bridge:{{ IMAGE_TAG }}
        ports:
        - containerPort: 30003
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-echo-http-bridge
  labels:
    app: grpc-echo
spec:
  type: NodePort
  ports:
    - port: 30003
      nodePort: 30003
      name: http
  selector:
    app: grpc-echo
    role: http-bridge
