#!/bin/bash
set -e                    # Always die on error
trap 'kill -HUP 0' SIGINT # Kill sub-processes when we're killed
cd "$PROJECTNAME_ROOT"    # Start script in project root

# This hook is called after a merge (e.g if `git pull` contains changes).

echo "*** misc/automate/git-hooks/post-merge: RUN setup-tools.sh"
bash $PROJECTNAME_ROOT/misc/automate/setup-tools.sh
