#!/bin/bash
set -e

# This hook is called after `git checkout` (e.g `git checkout -b feature-branch` or `git checkout master`)

echo "*** misc/automate/git-hooks/post-checkout: RUN setup-tools.sh"
bash $PROJECTNAME_ROOT/misc/automate/setup-tools.sh
