#!/bin/bash
source "$PROJECTNAME_ROOT/dev/_setup/boilerplates/base-bash-include.sh"

# This hook is called after a merge (e.g if `git pull` contains changes).

echo "*** dev/_setup/git-hooks/post-merge: TODO"
# bash $PROJECTNAME_ROOT/dev/_setup/setup-tools.sh
