---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-node
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: hello-node
        role: server
      annotations:
        time: "{{ TIME }}"
        git-sha: "{{ GIT-SHA }}"
        whoami: "{{ WHOAMI }}"
    spec:
      containers:
      - name: hello-node
        image: examples/hello-node:{{ IMAGE_TAG }}
        ports:
        - containerPort: 30002






---
apiVersion: v1
kind: Service
metadata:
  name: hello-node-service
  labels:
    app: hello-node
spec:
  type: NodePort
  ports:
    - port: 30002
      nodePort: 30002
      name: http
  selector:
    app: hello-node
    role: server
