#!/bin/bash
set -e                    # Always die on error
trap 'kill -HUP 0' SIGINT # Kill sub-processes when we're killed
cd "$PROJECTNAME_ROOT"    # Start script in project root

# This hook is called on `git commit -m "commit msg"`. If it exits with an error, the commit cancels.

echo "*** scripts/dev/automate-dev-env/git-hooks/pre-commit: TODO"
# bash $PROJECTNAME_ROOT/scripts/test/pre-commit.sh
