// Code generated by protoc-gen-go. DO NOT EDIT.
// source: examples/db/db.proto

/*
Package db is a generated protocol buffer package.

It is generated from these files:
	examples/db/db.proto

It has these top-level messages:
	Account
	Company
	AccountLookup
	AccountInvite
	FunnelStats
*/
package db

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AccountLookupFieldType int32

const (
	AccountLookupFieldType_ACCOUNT_LOOKUP_FIELD_TYPE_NONW AccountLookupFieldType = 0
	AccountLookupFieldType_FIRST_NAME                     AccountLookupFieldType = 1
	AccountLookupFieldType_MIDDLE_NAMES                   AccountLookupFieldType = 2
	AccountLookupFieldType_LAST_NAME                      AccountLookupFieldType = 3
	AccountLookupFieldType_PHONE_NUMBER                   AccountLookupFieldType = 4
	AccountLookupFieldType_EMAIL_ADDRESS                  AccountLookupFieldType = 5
)

var AccountLookupFieldType_name = map[int32]string{
	0: "ACCOUNT_LOOKUP_FIELD_TYPE_NONW",
	1: "FIRST_NAME",
	2: "MIDDLE_NAMES",
	3: "LAST_NAME",
	4: "PHONE_NUMBER",
	5: "EMAIL_ADDRESS",
}
var AccountLookupFieldType_value = map[string]int32{
	"ACCOUNT_LOOKUP_FIELD_TYPE_NONW": 0,
	"FIRST_NAME":                     1,
	"MIDDLE_NAMES":                   2,
	"LAST_NAME":                      3,
	"PHONE_NUMBER":                   4,
	"EMAIL_ADDRESS":                  5,
}

func (x AccountLookupFieldType) String() string {
	return proto.EnumName(AccountLookupFieldType_name, int32(x))
}
func (AccountLookupFieldType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type FunnelStep int32

const (
	FunnelStep_FUNNEL_STEP_NONE  FunnelStep = 0
	FunnelStep_ACCOUNT_IMPORTED  FunnelStep = 1
	FunnelStep_INVITE_SENT       FunnelStep = 2
	FunnelStep_INVITE_VIEWED     FunnelStep = 3
	FunnelStep_ENROLLED          FunnelStep = 4
	FunnelStep_ACCOUNT_VIEWED    FunnelStep = 5
	FunnelStep_CERT_VIEWED       FunnelStep = 6
	FunnelStep_BENEFICIARY_ADDED FunnelStep = 7
	FunnelStep_CLAIM_MADE        FunnelStep = 8
	FunnelStep_CLAIM_PAID        FunnelStep = 9
)

var FunnelStep_name = map[int32]string{
	0: "FUNNEL_STEP_NONE",
	1: "ACCOUNT_IMPORTED",
	2: "INVITE_SENT",
	3: "INVITE_VIEWED",
	4: "ENROLLED",
	5: "ACCOUNT_VIEWED",
	6: "CERT_VIEWED",
	7: "BENEFICIARY_ADDED",
	8: "CLAIM_MADE",
	9: "CLAIM_PAID",
}
var FunnelStep_value = map[string]int32{
	"FUNNEL_STEP_NONE":  0,
	"ACCOUNT_IMPORTED":  1,
	"INVITE_SENT":       2,
	"INVITE_VIEWED":     3,
	"ENROLLED":          4,
	"ACCOUNT_VIEWED":    5,
	"CERT_VIEWED":       6,
	"BENEFICIARY_ADDED": 7,
	"CLAIM_MADE":        8,
	"CLAIM_PAID":        9,
}

func (x FunnelStep) String() string {
	return proto.EnumName(FunnelStep_name, int32(x))
}
func (FunnelStep) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Account struct {
	// string created_time = 1;
	AccountId         int64  `protobuf:"varint,2,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	CompanyId         int64  `protobuf:"varint,3,opt,name=company_id,json=companyId" json:"company_id,omitempty"`
	ExternalAccountId string `protobuf:"bytes,4,opt,name=external_account_id,json=externalAccountId" json:"external_account_id,omitempty"`
	AccountData       []byte `protobuf:"bytes,5,opt,name=account_data,json=accountData,proto3" json:"account_data,omitempty"`
	PhoneNumber       string `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber" json:"phone_number,omitempty"`
	EmailAddress      string `protobuf:"bytes,7,opt,name=email_address,json=emailAddress" json:"email_address,omitempty"`
	FullName          string `protobuf:"bytes,8,opt,name=full_name,json=fullName" json:"full_name,omitempty"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Account) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *Account) GetCompanyId() int64 {
	if m != nil {
		return m.CompanyId
	}
	return 0
}

func (m *Account) GetExternalAccountId() string {
	if m != nil {
		return m.ExternalAccountId
	}
	return ""
}

func (m *Account) GetAccountData() []byte {
	if m != nil {
		return m.AccountData
	}
	return nil
}

func (m *Account) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Account) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *Account) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

type Company struct {
	// string created_time = 1;
	CompanyId     int64  `protobuf:"varint,2,opt,name=company_id,json=companyId" json:"company_id,omitempty"`
	CompanyMarker string `protobuf:"bytes,3,opt,name=company_marker,json=companyMarker" json:"company_marker,omitempty"`
	CompanyName   string `protobuf:"bytes,4,opt,name=company_name,json=companyName" json:"company_name,omitempty"`
}

func (m *Company) Reset()                    { *m = Company{} }
func (m *Company) String() string            { return proto.CompactTextString(m) }
func (*Company) ProtoMessage()               {}
func (*Company) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Company) GetCompanyId() int64 {
	if m != nil {
		return m.CompanyId
	}
	return 0
}

func (m *Company) GetCompanyMarker() string {
	if m != nil {
		return m.CompanyMarker
	}
	return ""
}

func (m *Company) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

type AccountLookup struct {
	// string created_time = 1;
	FieldType  AccountLookupFieldType `protobuf:"varint,2,opt,name=field_type,json=fieldType,enum=db.AccountLookupFieldType" json:"field_type,omitempty"`
	FieldValue string                 `protobuf:"bytes,3,opt,name=field_value,json=fieldValue" json:"field_value,omitempty"`
	AccountId  int64                  `protobuf:"varint,4,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
}

func (m *AccountLookup) Reset()                    { *m = AccountLookup{} }
func (m *AccountLookup) String() string            { return proto.CompactTextString(m) }
func (*AccountLookup) ProtoMessage()               {}
func (*AccountLookup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AccountLookup) GetFieldType() AccountLookupFieldType {
	if m != nil {
		return m.FieldType
	}
	return AccountLookupFieldType_ACCOUNT_LOOKUP_FIELD_TYPE_NONW
}

func (m *AccountLookup) GetFieldValue() string {
	if m != nil {
		return m.FieldValue
	}
	return ""
}

func (m *AccountLookup) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

type AccountInvite struct {
	AccountId int64  `protobuf:"varint,1,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	Secret    string `protobuf:"bytes,2,opt,name=secret" json:"secret,omitempty"`
	Claimed   bool   `protobuf:"varint,3,opt,name=claimed" json:"claimed,omitempty"`
}

func (m *AccountInvite) Reset()                    { *m = AccountInvite{} }
func (m *AccountInvite) String() string            { return proto.CompactTextString(m) }
func (*AccountInvite) ProtoMessage()               {}
func (*AccountInvite) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AccountInvite) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *AccountInvite) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *AccountInvite) GetClaimed() bool {
	if m != nil {
		return m.Claimed
	}
	return false
}

// message FunnelStep {
// 	FunnelStepType type = 1;
// 	int64 account_id = 2;
// }
type FunnelStats struct {
	AccountImported  int64 `protobuf:"varint,1,opt,name=account_imported,json=accountImported" json:"account_imported,omitempty"`
	InviteSent       int64 `protobuf:"varint,2,opt,name=invite_sent,json=inviteSent" json:"invite_sent,omitempty"`
	InviteViewed     int64 `protobuf:"varint,3,opt,name=invite_viewed,json=inviteViewed" json:"invite_viewed,omitempty"`
	Enrolled         int64 `protobuf:"varint,4,opt,name=enrolled" json:"enrolled,omitempty"`
	AccountViewed    int64 `protobuf:"varint,5,opt,name=account_viewed,json=accountViewed" json:"account_viewed,omitempty"`
	CertViewed       int64 `protobuf:"varint,6,opt,name=cert_viewed,json=certViewed" json:"cert_viewed,omitempty"`
	BeneficiaryAdded int64 `protobuf:"varint,7,opt,name=beneficiary_added,json=beneficiaryAdded" json:"beneficiary_added,omitempty"`
	ClaimMade        int64 `protobuf:"varint,8,opt,name=claim_made,json=claimMade" json:"claim_made,omitempty"`
	ClaimPaid        int64 `protobuf:"varint,9,opt,name=claim_paid,json=claimPaid" json:"claim_paid,omitempty"`
}

func (m *FunnelStats) Reset()                    { *m = FunnelStats{} }
func (m *FunnelStats) String() string            { return proto.CompactTextString(m) }
func (*FunnelStats) ProtoMessage()               {}
func (*FunnelStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *FunnelStats) GetAccountImported() int64 {
	if m != nil {
		return m.AccountImported
	}
	return 0
}

func (m *FunnelStats) GetInviteSent() int64 {
	if m != nil {
		return m.InviteSent
	}
	return 0
}

func (m *FunnelStats) GetInviteViewed() int64 {
	if m != nil {
		return m.InviteViewed
	}
	return 0
}

func (m *FunnelStats) GetEnrolled() int64 {
	if m != nil {
		return m.Enrolled
	}
	return 0
}

func (m *FunnelStats) GetAccountViewed() int64 {
	if m != nil {
		return m.AccountViewed
	}
	return 0
}

func (m *FunnelStats) GetCertViewed() int64 {
	if m != nil {
		return m.CertViewed
	}
	return 0
}

func (m *FunnelStats) GetBeneficiaryAdded() int64 {
	if m != nil {
		return m.BeneficiaryAdded
	}
	return 0
}

func (m *FunnelStats) GetClaimMade() int64 {
	if m != nil {
		return m.ClaimMade
	}
	return 0
}

func (m *FunnelStats) GetClaimPaid() int64 {
	if m != nil {
		return m.ClaimPaid
	}
	return 0
}

func init() {
	proto.RegisterType((*Account)(nil), "db.Account")
	proto.RegisterType((*Company)(nil), "db.Company")
	proto.RegisterType((*AccountLookup)(nil), "db.AccountLookup")
	proto.RegisterType((*AccountInvite)(nil), "db.AccountInvite")
	proto.RegisterType((*FunnelStats)(nil), "db.FunnelStats")
	proto.RegisterEnum("db.AccountLookupFieldType", AccountLookupFieldType_name, AccountLookupFieldType_value)
	proto.RegisterEnum("db.FunnelStep", FunnelStep_name, FunnelStep_value)
}

func init() { proto.RegisterFile("examples/db/db.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 745 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x94, 0xdf, 0x8e, 0xdb, 0x44,
	0x14, 0xc6, 0xeb, 0x64, 0x37, 0x89, 0x4f, 0x92, 0xed, 0xec, 0x50, 0xaa, 0xa8, 0x08, 0xba, 0x04,
	0x21, 0x2d, 0x45, 0xda, 0x4a, 0x70, 0xc5, 0xa5, 0x1b, 0x4f, 0x84, 0x85, 0xed, 0x44, 0xb6, 0x77,
	0xab, 0x5e, 0x0d, 0x93, 0xcc, 0x59, 0x61, 0xd5, 0xff, 0xe4, 0x38, 0x4b, 0xf3, 0x0a, 0x5c, 0xf2,
	0x50, 0xdc, 0xf1, 0x4c, 0xa0, 0x19, 0x8f, 0xb3, 0x4b, 0xc4, 0x9d, 0xe7, 0x77, 0xbe, 0x9c, 0xf3,
	0x9d, 0x99, 0x4f, 0x81, 0x17, 0xf8, 0x49, 0xe4, 0x55, 0x86, 0xbb, 0xb7, 0x72, 0xf3, 0x56, 0x6e,
	0x6e, 0xaa, 0xba, 0x6c, 0x4a, 0xda, 0x93, 0x9b, 0xf9, 0x3f, 0x16, 0x0c, 0x9d, 0xed, 0xb6, 0xdc,
	0x17, 0x0d, 0xfd, 0x12, 0x40, 0xb4, 0x9f, 0x3c, 0x95, 0xb3, 0xde, 0x95, 0x75, 0xdd, 0x8f, 0x6c,
	0x43, 0x3c, 0xa9, 0xca, 0xdb, 0x32, 0xaf, 0x44, 0x71, 0x50, 0xe5, 0x7e, 0x5b, 0x36, 0xc4, 0x93,
	0xf4, 0x06, 0x3e, 0xc3, 0x4f, 0x0d, 0xd6, 0x85, 0xc8, 0xf8, 0x93, 0x36, 0x67, 0x57, 0xd6, 0xb5,
	0x1d, 0x5d, 0x76, 0x25, 0xe7, 0xd8, 0xee, 0x6b, 0x98, 0x74, 0x32, 0x29, 0x1a, 0x31, 0x3b, 0xbf,
	0xb2, 0xae, 0x27, 0xd1, 0xd8, 0x30, 0x57, 0x34, 0x42, 0x49, 0xaa, 0xdf, 0xca, 0x02, 0x79, 0xb1,
	0xcf, 0x37, 0x58, 0xcf, 0x06, 0xba, 0xd7, 0x58, 0xb3, 0x50, 0x23, 0xfa, 0x0d, 0x4c, 0x31, 0x17,
	0x69, 0xc6, 0x85, 0x94, 0x35, 0xee, 0x76, 0xb3, 0xa1, 0xd6, 0x4c, 0x34, 0x74, 0x5a, 0x46, 0xbf,
	0x00, 0xfb, 0x7e, 0x9f, 0x65, 0xbc, 0x10, 0x39, 0xce, 0x46, 0x5a, 0x30, 0x52, 0x20, 0x14, 0x39,
	0xce, 0x6b, 0x18, 0x2e, 0xda, 0x25, 0x4e, 0x36, 0xec, 0x9d, 0x6e, 0xf8, 0x2d, 0x5c, 0x74, 0xe5,
	0x5c, 0xd4, 0x1f, 0xb1, 0xd6, 0x97, 0x60, 0x47, 0x53, 0x43, 0x03, 0x0d, 0x95, 0xeb, 0x4e, 0xa6,
	0x07, 0xb6, 0x37, 0x30, 0x36, 0x4c, 0xcf, 0xfc, 0xc3, 0x82, 0xa9, 0xb9, 0x09, 0xbf, 0x2c, 0x3f,
	0xee, 0x2b, 0xfa, 0x13, 0xc0, 0x7d, 0x8a, 0x99, 0xe4, 0xcd, 0xa1, 0x42, 0x3d, 0xfa, 0xe2, 0x87,
	0x57, 0x37, 0x72, 0x73, 0xf3, 0x1f, 0xd9, 0x52, 0x49, 0x92, 0x43, 0x85, 0x91, 0x7d, 0xdf, 0x7d,
	0xd2, 0xd7, 0x30, 0x6e, 0x7f, 0xfa, 0x20, 0xb2, 0x3d, 0x1a, 0x4f, 0x6d, 0xb7, 0x3b, 0x45, 0x4e,
	0xde, 0xf5, 0xec, 0xe4, 0x5d, 0xe7, 0xbf, 0x1e, 0xbd, 0x78, 0xc5, 0x43, 0xda, 0x9c, 0xea, 0xad,
	0xd3, 0x1c, 0xbc, 0x84, 0xc1, 0x0e, 0xb7, 0x35, 0x36, 0xda, 0xa6, 0x1d, 0x99, 0x13, 0x9d, 0xc1,
	0x70, 0x9b, 0x89, 0x34, 0xc7, 0x36, 0x1c, 0xa3, 0xa8, 0x3b, 0xce, 0xff, 0xee, 0xc1, 0x78, 0xb9,
	0x2f, 0x0a, 0xcc, 0xe2, 0x46, 0x34, 0x3b, 0xfa, 0x1d, 0x90, 0xe3, 0x80, 0xbc, 0x2a, 0xeb, 0x06,
	0xbb, 0x31, 0xcf, 0xbb, 0x31, 0x06, 0xab, 0xe5, 0x52, 0xed, 0x8a, 0xef, 0xb0, 0x68, 0xcc, 0x9b,
	0x40, 0x8b, 0x62, 0x2c, 0x1a, 0x15, 0x00, 0x23, 0x78, 0x48, 0xf1, 0x77, 0xec, 0x82, 0x39, 0x69,
	0xe1, 0x9d, 0x66, 0xf4, 0x15, 0x8c, 0xb0, 0xa8, 0xcb, 0x2c, 0xc3, 0x6e, 0xff, 0xe3, 0x59, 0xbd,
	0x6a, 0x67, 0xc6, 0x74, 0x38, 0xd7, 0x8a, 0xa9, 0xa1, 0xa6, 0xc5, 0x6b, 0x18, 0x6f, 0xb1, 0x3e,
	0x6a, 0x06, 0xad, 0x11, 0x85, 0x8c, 0xe0, 0x7b, 0xb8, 0xdc, 0x60, 0x81, 0xf7, 0xe9, 0x36, 0x15,
	0xf5, 0x41, 0xe5, 0x11, 0xa5, 0x4e, 0x63, 0x3f, 0x22, 0x4f, 0x0a, 0x8e, 0xe2, 0x3a, 0x69, 0xea,
	0x72, 0x78, 0x2e, 0x64, 0x1b, 0x49, 0x95, 0x34, 0x45, 0x02, 0x21, 0xf1, 0xb1, 0x5c, 0x89, 0x54,
	0xce, 0xec, 0x27, 0xe5, 0xb5, 0x48, 0xe5, 0x9b, 0x3f, 0x2d, 0x78, 0xf9, 0xff, 0xb9, 0xa0, 0x73,
	0xf8, 0xca, 0x59, 0x2c, 0x56, 0xb7, 0x61, 0xc2, 0xfd, 0xd5, 0xea, 0x97, 0xdb, 0x35, 0x5f, 0x7a,
	0xcc, 0x77, 0x79, 0xf2, 0x61, 0xcd, 0x78, 0xb8, 0x0a, 0xdf, 0x93, 0x67, 0xf4, 0x02, 0x60, 0xe9,
	0x45, 0x71, 0xc2, 0x43, 0x27, 0x60, 0xc4, 0xa2, 0x04, 0x26, 0x81, 0xe7, 0xba, 0x3e, 0xd3, 0x20,
	0x26, 0x3d, 0x3a, 0x05, 0xdb, 0x77, 0x3a, 0x41, 0x5f, 0x09, 0xd6, 0x3f, 0xaf, 0x42, 0xc6, 0xc3,
	0xdb, 0xe0, 0x1d, 0x8b, 0xc8, 0x19, 0xbd, 0x84, 0x29, 0x0b, 0x1c, 0xcf, 0xe7, 0x8e, 0xeb, 0x46,
	0x2c, 0x8e, 0xc9, 0xf9, 0x9b, 0xbf, 0x2c, 0x80, 0xee, 0x91, 0xb1, 0xa2, 0x2f, 0x80, 0x2c, 0x6f,
	0xc3, 0x90, 0xf9, 0x3c, 0x4e, 0xd8, 0x5a, 0x8d, 0x66, 0xe4, 0x99, 0xa2, 0x9d, 0x3d, 0x2f, 0x58,
	0xaf, 0xa2, 0x84, 0xb9, 0xc4, 0xa2, 0xcf, 0x61, 0xec, 0x85, 0x77, 0x5e, 0xc2, 0x78, 0xcc, 0xc2,
	0x84, 0xf4, 0x54, 0x7b, 0x03, 0xee, 0x3c, 0xf6, 0x9e, 0xb9, 0xa4, 0x4f, 0x27, 0x30, 0x62, 0x61,
	0xb4, 0xf2, 0x7d, 0xe6, 0x92, 0x33, 0x4a, 0xe1, 0xa2, 0xeb, 0x63, 0x14, 0xe7, 0xaa, 0xcb, 0x82,
	0x45, 0x47, 0x30, 0xa0, 0x9f, 0xc3, 0xe5, 0x3b, 0x16, 0xb2, 0xa5, 0xb7, 0xf0, 0x9c, 0xe8, 0x83,
	0xb2, 0xca, 0x5c, 0x32, 0x54, 0xeb, 0x2f, 0x7c, 0xc7, 0x0b, 0x78, 0xe0, 0xb8, 0x8c, 0x8c, 0x1e,
	0xcf, 0x6b, 0xc7, 0x73, 0x89, 0xbd, 0x19, 0xe8, 0x7f, 0xc7, 0x1f, 0xff, 0x0d, 0x00, 0x00, 0xff,
	0xff, 0xcc, 0x76, 0x39, 0xbf, 0x35, 0x05, 0x00, 0x00,
}
